In [1]:
import pandas as pd
from corpus import build_corpus
from datasets import load_dataset
import tiktoken
from chunking import chunk_corpus
from vector_store import *
from classical_rag import classical_rag
from agentic_rag import agentic_rag

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

In [3]:
df=pd.read_parquet("../data/processed/df_val_enriched.parquet")

In [39]:
corpus=build_corpus(df)

In [40]:
print(list(corpus.items())[:5])
print("length of the global corpus : ",len(corpus))
print("average length of the documents in the corpus : ",sum(len(x) for x in corpus.values())/len(corpus))

[('Ed Wood (film)', "Ed Wood is a 1994 American biographical period comedy-drama film directed and produced by Tim Burton, and starring Johnny Depp as cult filmmaker Ed Wood.  The film concerns the period in Wood's life when he made his best-known films as well as his relationship with actor Bela Lugosi, played by Martin Landau.  Sarah Jessica Parker, Patricia Arquette, Jeffrey Jones, Lisa Marie, and Bill Murray are among the supporting cast."), ('Scott Derrickson', 'Scott Derrickson (born July 16, 1966) is an American director, screenwriter and producer.  He lives in Los Angeles, California.  He is best known for directing horror films such as "Sinister", "The Exorcism of Emily Rose", and "Deliver Us From Evil", as well as the 2016 Marvel Cinematic Universe installment, "Doctor Strange."'), ('Woodson, Arkansas', 'Woodson is a census-designated place (CDP) in Pulaski County, Arkansas, in the United States.  Its population was 403 at the 2010 census.  It is part of the Little Rock–North Little Rock–Conway Metropolitan Statistical Area.  Woodson and its accompanying Woodson Lake and Wood Hollow are the namesake for Ed Wood Sr., a prominent plantation owner, trader, and businessman at the turn of the 20th century.  Woodson is adjacent to the Wood Plantation, the largest of the plantations own by Ed Wood Sr.'), ('Tyler Bates', 'Tyler Bates (born June 5, 1965) is an American musician, music producer, and composer for films, television, and video games.  Much of his work is in the action and horror film genres, with films like "Dawn of the Dead, 300, Sucker Punch," and "John Wick."  He has collaborated with directors like Zack Snyder, Rob Zombie, Neil Marshall, William Friedkin, Scott Derrickson, and James Gunn.  With Gunn, he has scored every one of the director\'s films; including "Guardians of the Galaxy", which became one of the highest grossing domestic movies of 2014, and its 2017 sequel.  In addition, he is also the lead guitarist of the American rock band Marilyn Manson, and produced its albums "The Pale Emperor" and "Heaven Upside Down".'), ('Ed Wood', 'Edward Davis Wood Jr. (October 10, 1924 – December 10, 1978) was an American filmmaker, actor, writer, producer, and director.')]
length of the global corpus :  66581
average length of the documents in the corpus :  534.8789594629098

In [41]:
enc=tiktoken.get_encoding("cl100k_base")
length_encoded=[]
for text in corpus.values():
    text_encoded=enc.encode(text)
    length_encoded.append(len(text_encoded))

pd.Series(length_encoded).describe()

count    66581.000000
mean       125.304606
std         71.231108
min          8.000000
25%         77.000000
50%        112.000000
75%        158.000000
max       1979.000000
dtype: float64

In [42]:
m=(pd.Series(length_encoded)>300).sum()
print("Number of documents with length greater than 300 : ",m)

Number of documents with length greater than 300 :  1541

In [20]:
df

,id,question,answer,type,level,supporting_facts,context,num_gold_paragraphs,num_titles_in_question,number_sf_in_context
0,5a8b57f25542995d1e6f1371,Were Scott Derrickson and Ed Wood of the same ...,yes,comparison,hard,"{'title': ['Scott Derrickson', 'Ed Wood'], 'se...","{'title': ['Ed Wood (film)', 'Scott Derrickson...",2,2,2
1,5a8c7595554299585d9e36b6,What government position was held by the woman...,Chief of Protocol,bridge,hard,"{'title': ['Kiss and Tell (1945 film)', 'Shirl...","{'title': ['Meet Corliss Archer', 'Shirley Tem...",2,0,2
2,5a85ea095542994775f606a8,"What science fantasy young adult series, told ...",Animorphs,bridge,hard,"{'title': ['The Hork-Bajir Chronicles', 'The H...","{'title': ['Andre Norton Award', 'Victoria Han...",2,0,2
3,5adbf0a255429947ff17385a,Are the Laleli Mosque and Esma Sultan Mansion ...,no,comparison,hard,"{'title': ['Laleli Mosque', 'Esma Sultan Mansi...",{'title': ['Esma Sultan (daughter of Abdülaziz...,2,2,2
4,5a8e3ea95542995a26add48d,"The director of the romantic comedy ""Big Stone...","Greenwich Village, New York City",bridge,hard,"{'title': ['Big Stone Gap (film)', 'Adriana Tr...",{'title': ['Just Another Romantic Wrestling Co...,2,0,2
...,...,...,...,...,...,...,...,...,...,...
7400,5ab92307554299753720f72d,What Pakistani actor and writer from Islamabad...,Yasir Hussain,bridge,hard,"{'title': ['Coke Kahani', 'Coke Kahani', 'Yasi...","{'title': ['Coke Kahani', 'Adnan Siddiqui', 'F...",2,1,2
7401,5abba3b1554299642a094aed,Are both Volvic and Canfield's Diet Chocolate ...,no,comparison,hard,"{'title': ['Volvic (mineral water)', 'Canfield...","{'title': ['ZERO bar', 'Pseudomonas mandelii',...",2,1,2
7402,5a8173fa554299260e20a28e,Are Billy and Barak both breeds of scenthound?...,yes,comparison,hard,"{'title': ['Bosnian Coarse-haired Hound', 'Bil...","{'title': ['Styrian Coarse-haired Hound', 'Bil...",2,1,2
7403,5a8caf1d554299585d9e3720,Were both of the following rock groups formed ...,yes,comparison,hard,"{'title': ['Dig (band)', 'Thinking Fellers Uni...","{'title': ['Strangers from the Universe', 'Mot...",2,1,2
7404,5ac132a755429964131be17c,Blackfin is a family of processors developed b...,"Norwood, Massachusetts",bridge,hard,"{'title': ['Blackfin', 'Analog Devices'], 'sen...","{'title': ['1st Word/1st Word Plus', 'Arm Hold...",2,1,2

In [47]:
pilot=df.groupby(['type','num_titles_in_question']).apply(lambda g : g.sample(n=25,random_state=4))

In [48]:
pilot=pilot.reset_index(drop=False)
print(pilot.index)
print(pilot.columns)
pilot

RangeIndex(start=0, stop=150, step=1)
Index(['type', 'num_titles_in_question', 'level_2', 'id', 'question', 'answer',
       'level', 'supporting_facts', 'context', 'num_gold_paragraphs',
       'number_sf_in_context'],
      dtype='str')

,type,num_titles_in_question,level_2,id,question,answer,level,supporting_facts,context,num_gold_paragraphs,number_sf_in_context
0,bridge,0,6099,5ade66f055429939a52fe8a0,Easter Airways' head office is located at whic...,Humberside Airport,hard,"{'title': ['Eastern Airways', 'Humberside Airp...","{'title': ['Manchester Interchange', 'Islay Ai...",2,2
1,bridge,0,1464,5a7f924c55429969796c1aba,Which Star of British-Canadian-American satiri...,Eric Banadinović,hard,"{'title': ['Special Correspondents', 'Eric Ban...","{'title': ['John Walker (Australian actor)', '...",2,2
2,bridge,0,946,5adfda5255429942ec259b5e,What county in Minnesota holds a 202 lb slab o...,Douglas,hard,"{'title': ['Kensington, Minnesota', 'Kensingto...","{'title': ['Bridge No. 3355-Kathio Township', ...",2,2
3,bridge,0,6589,5ae4e29855429908b63264a9,Where does the team that Flavio de Jesús Santo...,city of Culiacán,hard,"{'title': ['Flavio Santos', 'Dorados de Sinalo...","{'title': ['Adelaide Comets FC', 'Sheffield We...",2,2
4,bridge,0,888,5ab8ed305542991b5579f046,Keene is an unincorporated community in Wabaun...,The United States of America,hard,"{'title': ['Keene, Kansas', 'United States'], ...","{'title': ['United States', 'Administrative di...",2,2
...,...,...,...,...,...,...,...,...,...,...,...
145,comparison,2,6141,5ab2b7405542991669774069,Have James Schuyler and H. G. Wells both publi...,yes,hard,"{'title': ['James Schuyler', 'H. G. Wells'], '...","{'title': ['H. G. Wells', 'Pierre Martory', 'C...",2,2
146,comparison,2,3812,5a84d2ea5542992a431d1aa8,What career titles do Ed Wood and Fernand Rive...,"actor, writer, producer, and director",hard,"{'title': ['Ed Wood', 'Fernand Rivers'], 'sent...","{'title': ['Ed Wood', 'The Two Boys (1936 film...",2,2
147,comparison,2,1491,5a8dad37554299068b959d94,Both Phaedranassa and Mitella are considered t...,genus,hard,"{'title': ['Phaedranassa', 'Mitella'], 'sent_i...","{'title': ['Asiatosuchus', 'Ardipithecus kadab...",2,2
148,comparison,2,1227,5a79e3925542994bb9457130,Name three best sellers from Arthur Hailey tha...,"Hotel"" (1965), ""Airport"" (1968), ""Wheels"" (1971)",hard,"{'title': ['Arthur Hailey', 'Donna Tartt'], 's...","{'title': ['Arthur Hailey', 'Airport (1970 fil...",2,2
149,comparison,2,6284,5ae40b2b55429970de88d8b3,In between Polytechnic University of the Phil...,California Polytechnic State University,hard,{'title': ['Polytechnic University of the Phil...,"{'title': ['Cal Poly Mustangs men's soccer', '...",2,2

In [50]:
pilot=pilot.drop(columns=["level_2"])
pilot

,type,num_titles_in_question,id,question,answer,level,supporting_facts,context,num_gold_paragraphs,number_sf_in_context
0,bridge,0,5ade66f055429939a52fe8a0,Easter Airways' head office is located at whic...,Humberside Airport,hard,"{'title': ['Eastern Airways', 'Humberside Airp...","{'title': ['Manchester Interchange', 'Islay Ai...",2,2
1,bridge,0,5a7f924c55429969796c1aba,Which Star of British-Canadian-American satiri...,Eric Banadinović,hard,"{'title': ['Special Correspondents', 'Eric Ban...","{'title': ['John Walker (Australian actor)', '...",2,2
2,bridge,0,5adfda5255429942ec259b5e,What county in Minnesota holds a 202 lb slab o...,Douglas,hard,"{'title': ['Kensington, Minnesota', 'Kensingto...","{'title': ['Bridge No. 3355-Kathio Township', ...",2,2
3,bridge,0,5ae4e29855429908b63264a9,Where does the team that Flavio de Jesús Santo...,city of Culiacán,hard,"{'title': ['Flavio Santos', 'Dorados de Sinalo...","{'title': ['Adelaide Comets FC', 'Sheffield We...",2,2
4,bridge,0,5ab8ed305542991b5579f046,Keene is an unincorporated community in Wabaun...,The United States of America,hard,"{'title': ['Keene, Kansas', 'United States'], ...","{'title': ['United States', 'Administrative di...",2,2
...,...,...,...,...,...,...,...,...,...,...
145,comparison,2,5ab2b7405542991669774069,Have James Schuyler and H. G. Wells both publi...,yes,hard,"{'title': ['James Schuyler', 'H. G. Wells'], '...","{'title': ['H. G. Wells', 'Pierre Martory', 'C...",2,2
146,comparison,2,5a84d2ea5542992a431d1aa8,What career titles do Ed Wood and Fernand Rive...,"actor, writer, producer, and director",hard,"{'title': ['Ed Wood', 'Fernand Rivers'], 'sent...","{'title': ['Ed Wood', 'The Two Boys (1936 film...",2,2
147,comparison,2,5a8dad37554299068b959d94,Both Phaedranassa and Mitella are considered t...,genus,hard,"{'title': ['Phaedranassa', 'Mitella'], 'sent_i...","{'title': ['Asiatosuchus', 'Ardipithecus kadab...",2,2
148,comparison,2,5a79e3925542994bb9457130,Name three best sellers from Arthur Hailey tha...,"Hotel"" (1965), ""Airport"" (1968), ""Wheels"" (1971)",hard,"{'title': ['Arthur Hailey', 'Donna Tartt'], 's...","{'title': ['Arthur Hailey', 'Airport (1970 fil...",2,2
149,comparison,2,5ae40b2b55429970de88d8b3,In between Polytechnic University of the Phil...,California Polytechnic State University,hard,{'title': ['Polytechnic University of the Phil...,"{'title': ['Cal Poly Mustangs men's soccer', '...",2,2

In [52]:
final_corpus=chunk_corpus(corpus,threshold=300)

In [55]:
print("Shape of final corpus:", final_corpus.shape)
final_corpus

Shape of final corpus: (68211, 4)

,chunk_id,title,chunk_index,text
0,Ed Wood (film)_0,Ed Wood (film),0,Ed Wood is a 1994 American biographical period...
1,Scott Derrickson_0,Scott Derrickson,0,"Scott Derrickson (born July 16, 1966) is an Am..."
2,"Woodson, Arkansas_0","Woodson, Arkansas",0,Woodson is a census-designated place (CDP) in ...
3,Tyler Bates_0,Tyler Bates,0,"Tyler Bates (born June 5, 1965) is an American..."
4,Ed Wood_0,Ed Wood,0,"Edward Davis Wood Jr. (October 10, 1924 – Dece..."
...,...,...,...,...
68206,Analog Devices_0,Analog Devices,0,"Analog Devices, Inc., also known as ADI or Ana..."
68207,Zet (hardware)_0,Zet (hardware),0,Zet is a clone x86 processor where its machine...
68208,Xetal_0,Xetal,0,Xetal is the name of a family of non commercia...
68209,XAP processor_0,XAP processor,0,The XAP processor is a RISC processor architec...
68210,Blackfin_0,Blackfin,0,The Blackfin is a family of 16- or 32-bit micr...

In [56]:
pilot.to_parquet("../data/processed/pilot.parquet")
final_corpus.to_parquet("../data/processed/final_corpus.parquet")

In [5]:
final_corpus=pd.read_parquet("../data/processed/final_corpus.parquet")

In [7]:
final_corpus
final_corpus_embed=get_embeddings(final_corpus)

Batches:   0%|          | 0/2132 [00:00<?, ?it/s]

In [8]:
final_corpus_embed

,chunk_id,title,chunk_index,text,embeddings
0,Ed Wood (film)_0,Ed Wood (film),0,Ed Wood is a 1994 American biographical period...,"[-0.0051703453, 0.019602325, -0.031824153, 0.0..."
1,Scott Derrickson_0,Scott Derrickson,0,"Scott Derrickson (born July 16, 1966) is an Am...","[0.002950991, -0.022987213, -0.005424717, -0.0..."
2,"Woodson, Arkansas_0","Woodson, Arkansas",0,Woodson is a census-designated place (CDP) in ...,"[0.023222366, 0.016508676, -0.05767146, -0.033..."
3,Tyler Bates_0,Tyler Bates,0,"Tyler Bates (born June 5, 1965) is an American...","[0.0015271629, -0.00393534, -0.038948067, 0.07..."
4,Ed Wood_0,Ed Wood,0,"Edward Davis Wood Jr. (October 10, 1924 – Dece...","[0.011546341, -0.021726314, -0.023861984, 0.00..."
...,...,...,...,...,...
68206,Analog Devices_0,Analog Devices,0,"Analog Devices, Inc., also known as ADI or Ana...","[-0.002939147, -0.01783917, -0.043529715, 0.02..."
68207,Zet (hardware)_0,Zet (hardware),0,Zet is a clone x86 processor where its machine...,"[-0.0324406, -0.013010039, -0.026541445, 0.032..."
68208,Xetal_0,Xetal,0,Xetal is the name of a family of non commercia...,"[-0.064489804, 0.008572435, -0.019860506, 0.07..."
68209,XAP processor_0,XAP processor,0,The XAP processor is a RISC processor architec...,"[-0.063907765, -0.011429355, -0.053076703, 0.0..."
68210,Blackfin_0,Blackfin,0,The Blackfin is a family of 16- or 32-bit micr...,"[-0.052042365, -0.06648164, -0.066811174, 0.00..."

In [9]:
final_corpus_embed.to_parquet("../data/processed/final_corpus_embed.parquet")

In [2]:
final_corpus_embed=pd.read_parquet("../data/processed/final_corpus_embed.parquet")
final_corpus_embed

,chunk_id,title,chunk_index,text,embeddings
0,Ed Wood (film)_0,Ed Wood (film),0,Ed Wood is a 1994 American biographical period...,"[-0.0051703453, 0.019602325, -0.031824153, 0.0..."
1,Scott Derrickson_0,Scott Derrickson,0,"Scott Derrickson (born July 16, 1966) is an Am...","[0.002950991, -0.022987213, -0.005424717, -0.0..."
2,"Woodson, Arkansas_0","Woodson, Arkansas",0,Woodson is a census-designated place (CDP) in ...,"[0.023222366, 0.016508676, -0.05767146, -0.033..."
3,Tyler Bates_0,Tyler Bates,0,"Tyler Bates (born June 5, 1965) is an American...","[0.0015271629, -0.00393534, -0.038948067, 0.07..."
4,Ed Wood_0,Ed Wood,0,"Edward Davis Wood Jr. (October 10, 1924 – Dece...","[0.011546341, -0.021726314, -0.023861984, 0.00..."
...,...,...,...,...,...
68206,Analog Devices_0,Analog Devices,0,"Analog Devices, Inc., also known as ADI or Ana...","[-0.002939147, -0.01783917, -0.043529715, 0.02..."
68207,Zet (hardware)_0,Zet (hardware),0,Zet is a clone x86 processor where its machine...,"[-0.0324406, -0.013010039, -0.026541445, 0.032..."
68208,Xetal_0,Xetal,0,Xetal is the name of a family of non commercia...,"[-0.064489804, 0.008572435, -0.019860506, 0.07..."
68209,XAP processor_0,XAP processor,0,The XAP processor is a RISC processor architec...,"[-0.063907765, -0.011429355, -0.053076703, 0.0..."
68210,Blackfin_0,Blackfin,0,The Blackfin is a family of 16- or 32-bit micr...,"[-0.052042365, -0.06648164, -0.066811174, 0.00..."

In [14]:
index=build_index(final_corpus_embed)
index

In [15]:
save_index(index,"../data/processed/VectorDB.index")

In [3]:
pilot=pd.read_parquet("../data/processed/pilot.parquet")

In [4]:
pilot

,type,num_titles_in_question,id,question,answer,level,supporting_facts,context,num_gold_paragraphs,number_sf_in_context
0,bridge,0,5ade66f055429939a52fe8a0,Easter Airways' head office is located at whic...,Humberside Airport,hard,"{'title': ['Eastern Airways', 'Humberside Airp...","{'title': ['Manchester Interchange', 'Islay Ai...",2,2
1,bridge,0,5a7f924c55429969796c1aba,Which Star of British-Canadian-American satiri...,Eric Banadinović,hard,"{'title': ['Special Correspondents', 'Eric Ban...","{'title': ['John Walker (Australian actor)', '...",2,2
2,bridge,0,5adfda5255429942ec259b5e,What county in Minnesota holds a 202 lb slab o...,Douglas,hard,"{'title': ['Kensington, Minnesota', 'Kensingto...","{'title': ['Bridge No. 3355-Kathio Township', ...",2,2
3,bridge,0,5ae4e29855429908b63264a9,Where does the team that Flavio de Jesús Santo...,city of Culiacán,hard,"{'title': ['Flavio Santos', 'Dorados de Sinalo...","{'title': ['Adelaide Comets FC', 'Sheffield We...",2,2
4,bridge,0,5ab8ed305542991b5579f046,Keene is an unincorporated community in Wabaun...,The United States of America,hard,"{'title': ['Keene, Kansas', 'United States'], ...","{'title': ['United States', 'Administrative di...",2,2
...,...,...,...,...,...,...,...,...,...,...
145,comparison,2,5ab2b7405542991669774069,Have James Schuyler and H. G. Wells both publi...,yes,hard,"{'title': ['James Schuyler', 'H. G. Wells'], '...","{'title': ['H. G. Wells', 'Pierre Martory', 'C...",2,2
146,comparison,2,5a84d2ea5542992a431d1aa8,What career titles do Ed Wood and Fernand Rive...,"actor, writer, producer, and director",hard,"{'title': ['Ed Wood', 'Fernand Rivers'], 'sent...","{'title': ['Ed Wood', 'The Two Boys (1936 film...",2,2
147,comparison,2,5a8dad37554299068b959d94,Both Phaedranassa and Mitella are considered t...,genus,hard,"{'title': ['Phaedranassa', 'Mitella'], 'sent_i...","{'title': ['Asiatosuchus', 'Ardipithecus kadab...",2,2
148,comparison,2,5a79e3925542994bb9457130,Name three best sellers from Arthur Hailey tha...,"Hotel"" (1965), ""Airport"" (1968), ""Wheels"" (1971)",hard,"{'title': ['Arthur Hailey', 'Donna Tartt'], 's...","{'title': ['Arthur Hailey', 'Airport (1970 fil...",2,2
149,comparison,2,5ae40b2b55429970de88d8b3,In between Polytechnic University of the Phil...,California Polytechnic State University,hard,{'title': ['Polytechnic University of the Phil...,"{'title': ['Cal Poly Mustangs men's soccer', '...",2,2

In [21]:
question=pilot["question"][0]
print(question)
res=search_index(index,question,final_corpus_embed,k=5)
res

Easter Airways' head office is located at which airport owned by Manchester Airports Group?

,chunk_id,title,chunk_index,text,embeddings,score
57173,Manchester Airports Group_0,Manchester Airports Group,0,The Manchester Airports Group plc (MAG) is a h...,"[0.017928362, 0.05039166, -0.031164998, -0.033...",0.652407
8601,Eastern Airways_0,Eastern Airways,0,"Air Kilroe Limited, trading as Eastern Airways...","[-0.017321013, 0.016849758, -0.0052506593, -0....",0.581311
55545,Manchester–Boston Regional Airport_0,Manchester–Boston Regional Airport,0,"Manchester–Boston Regional Airport (IATA: MHT,...","[0.014803063, 0.007669145, -0.03716302, 0.0029...",0.578432
57174,BA CityFlyer_0,BA CityFlyer,0,BA CityFlyer is a wholly owned subsidiary airl...,"[-0.033040285, -0.013829669, -0.026209746, -0....",0.564113
57171,Humberside Airport_0,Humberside Airport,0,"Humberside Airport (IATA: HUY, ICAO: EGNJ) is ...","[-0.0439363, 0.05076909, -0.0075923684, -0.020...",0.556118

In [26]:
truth=set(pilot["supporting_facts"][0]["title"])
print(sum(1 for t in truth if t in res['title'].values))

2

In [33]:
def search_it(df): 
    res=search_index(index,df["question"],final_corpus_embed,5)
    truth=set(df["supporting_facts"]["title"])
    return sum(1 for t in truth if t in res['title'].values)


pilot["recall@5"]=pilot.apply(search_it,axis=1)/pilot["num_gold_paragraphs"]

In [34]:
pilot.groupby(["type","num_titles_in_question"])["recall@5"].mean()

type        num_titles_in_question
bridge      0                         0.70
            1                         0.76
            2                         0.96
comparison  0                         0.94
            1                         0.96
            2                         0.94
Name: recall@5, dtype: float64

In [4]:
pilot_sample=pilot.sample(n=10,random_state=42)
results=await agentic_rag(pilot_sample)
results

[{'id': '5ab822ef55429916710eafff',
  'question': 'Stephen Sondheim and Thomas Z. Shepard both worked in the production of what genre of music?',
  'hop_counter': 1,
  'answer': 'musical theatre',
  'titles': ['Thomas Z. Shepard',
   'Stephen Sondheim',
   'Passion (musical)',
   'Sondheim on Sondheim',
   'Six by Sondheim'],
  'context': ['Thomas Z. Shepard is a prolific record producer who is best known for his recordings of Broadway musicals, including the works of Stephen Sondheim.  Shepard is also a composer, conductor, music arranger and pianist.',
   'Stephen Joshua Sondheim ( ; born March 22, 1930) is an American composer and lyricist known for more than a half-century of contributions to musical theatre.  Sondheim has received an Academy Award, eight Tony Awards (more than any other composer, including a Special Tony Award for Lifetime Achievement in the Theatre), eight Grammy Awards, a Pulitzer Prize, a Laurence Olivier Award, and a 2015 Presidential Medal of Freedom.  He has been described by Frank Rich of "The New York Times" as "now the greatest and perhaps best-known artist in the American musical theater."  His best-known works as composer and lyricist include "A Funny Thing Happened on the Way to the Forum", "Company", "Follies", "A Little Night Music", "Pacific Overtures", "", "Merrily We Roll Along", "Sunday in the Park with George", "Into the Woods", "Assassins", and "Passion".  He also wrote the lyrics for "West Side Story" and "Gypsy".',
   'Passion is a one-act musical, with music and lyrics by Stephen Sondheim and a book by James Lapine.  The story was adapted from Ettore Scola\'s film "Passione d\'Amore", itself adapted from the novel "Fosca" by Iginio Ugo Tarchetti.  Central themes include love, sex, obsession, illness, passion, beauty, power and manipulation.  "Passion" is notable for being one of the few projects that Stephen Sondheim himself conceived, along with "Sweeney Todd" and "Road Show".',
   'Sondheim on Sondheim is a musical revue consisting of music and lyrics written by Stephen Sondheim for his many shows.  It is conceived and directed by James Lapine.  The revue had a limited run on Broadway in 2010.',
   'Six by Sondheim is an HBO television documentary which pays tribute to Broadway composer and lyricist Stephen Sondheim.  The film was directed and co-produced by James Lapine, based on an idea by Frank Rich and "centers on the backstory of six great Sondheim songs."'],
  'latency': 0.223342033001245,
  'type': 'bridge',
  'num_titles_in_question': 2,
  'prompt_tokens': 584,
  'completion_tokens': 4,
  'search': False},
 {'id': '5ab57673554299637185c5a3',
  'question': 'What public service broadcaster with over 20,950 employees, aired the variety show Welsh Rarebit?',
  'hop_counter': 1,
  'answer': 'BBC',
  'titles': ['Welsh Rarebit (radio programme)',
   'BBC',
   'Eynon Evans',
   'Raidió Teilifís Éireann',
   'Keith Walsh'],
  'context': ['Welsh Rarebit was a radio variety show broadcast from Cardiff by the BBC between February 1940 and December 1952.  The title was taken from that of the Welsh dish of the same name.  The show\'s most lasting legacy remains its closing song, "We\'ll Keep a Welcome (in the Hillsides)".',
   "The British Broadcasting Corporation (BBC) is a British public service broadcaster with its headquarters at Broadcasting House in London.  The BBC is the world's oldest national broadcasting organisation and the largest broadcaster in the world by number of employees.  It employs over 20,950 staff in total, 16,672 of whom are in public sector broadcasting.  The total number of staff is 35,402 when part-time, flexible, and fixed contract staff are included.",
   'Eynon Evans also known as E. Eynon Rees (18 May 1904 – 1989) was a Welsh writer and film actor of the 1950s, mainly known for his radio and television work.  During the 1940s he appeared on the BBC radio variety show "Welsh Rarebit" as the comedic character Tommy Troubles, reaching an audience of 12 million.',
   'Raidió Teilifís Éireann (] ; "Radio [and] Television of Ireland"; abbreviated as RTÉ) is a semi-state company and the national public service broadcaster of the Republic of Ireland.  It both produces programmes and broadcasts them on television, radio and the Internet.  The radio service began on 1 January 1926, while regular television broadcasts began on 31 December 1961, making it one of the oldest continuously operating public service broadcasters in the world.  RTÉ also publishes a weekly lifestyle magazine called the "RTÉ Guide".',
   'Keith Walsh is an Irish radio DJ, and Vegan.  Currently the lead anchor for RTÉ 2fm\'s early morning programme "Breakfast Republic" with comedians Bernard O\'Shea and Jennifer Maguire.  Walsh earlier worked at Dublin\'s SPIN 1038 where he partnered with Joe Donnelly.  He is a former programme director for i105107 and Phantom 105.2.  He is married and has two children.'],
  'latency': 0.14906626499578124,
  'type': 'bridge',
  'num_titles_in_question': 0,
  'prompt_tokens': 584,
  'completion_tokens': 2,
  'search': False},
 {'id': '5a84d80c5542992a431d1ab5',
  'question': 'Which building is used for more different uses, MiMA or 270 Park Avenue?',
  'hop_counter': 1,
  'answer': 'MiMA',
  'titles': ['270 Park Avenue',
   '277 Park Avenue',
   'MiMA (building)',
   '245 Park Avenue',
   '432 Park Avenue'],
  'context': ['270 Park Avenue (also known as the JPMorgan Chase Tower and formerly the Union Carbide Building) is a high-rise office building located in Midtown Manhattan, New York City.  It was designed by Natalie de Blois for Skidmore, Owings & Merrill.',
   '277 Park Avenue is an office building in the Midtown Manhattan neighborhood of New York City.  It stands on the east side of Park Avenue between East 47th and 48th Streets; it is 687 ft tall, with 50 floors.',
   'MiMA, which stands for "Middle of Manhattan", is a mixed-use building located at 450 West 42nd Street between Dyer and 10th Avenues in the Hell\'s Kitchen neighborhood of Manhattan, New York City.  Ground was broken in 2007 and topping out occurred in early August 2010.  It was designed by the Miami-based architecture firm of Arquitectonica, and has 43 floors of luxury rentals on floors 7 to 50, twelve floors of condominiums on floors 51 to 63, and a Yotel hotel on the lower levels.  The building\'s height is 204 meters (670 feet).',
   '245 Park Avenue (formerly American Tobacco Company Building, American Brands Building and Bear Stearns Building) is a 648-ft (198 m) tall skyscraper in New York City, New York.  It was completed in 1967 and has 48 floors (1.7 million square feet).  Shreve, Lamb and Harmon designed the building.  The Building Owners and Managers Association awarded the 2000/2001 Pinnacle Award to 245 Park Avenue.  The site used to be occupied by the second Grand Central Palace exhibition hall, which was demolished in 1964 to make way for 245 Park Avenue.',
   '432 Park Avenue is a residential skyscraper in New York City that overlooks Central Park.  Originally proposed to be 1300 ft in 2011, the structure topped out at 1396 ft .  It was developed by CIM Group and features 104 condominium apartments.  Construction began in 2012 and was completed on December 23, 2015.'],
  'latency': 0.16076578699721722,
  'type': 'comparison',
  'num_titles_in_question': 1,
  'prompt_tokens': 596,
  'completion_tokens': 3,
  'search': False},
 {'id': '5ab344fc55429969a97a811e',
  'question': 'Do Bloody Mary and Sidecar share any ingredients in common?',
  'hop_counter': 3,
  'answer': 'Worcestershire sauce',
  'titles': ['Sidecar (cocktail)',
   'Bloody Mary (South Park)',
   'Bloody Mary (Nerve Endings)',
   'Bloody Mary (cocktail)',
   'The Bloody Mary Show',
   'Thinks ...',
   'Arriving Somewhere...',
   'Daniel Romer',
   'Koi... Mil Gaya',
   'After... (visual novel)',
   'Thinks ...',
   'Arriving Somewhere...',
   'Daniel Romer',
   'Koi... Mil Gaya',
   'After... (visual novel)'],
  'context': ['The sidecar is a cocktail traditionally made with cognac, orange liqueur (Cointreau, Grand Marnier, Grand Gala or another triple sec), and lemon juice.  In its ingredients, the drink is perhaps most closely related to the older brandy crusta, which differs both in presentation and in proportions of its components.',
   '"Bloody Mary" is the fourteenth episode in the ninth season of the American animated television series "South Park".  The 139th overall episode of the series, it originally aired on Comedy Central in the United States on December 7, 2005.  In the episode, Randy drives drunk and loses his driver\'s license.  He is then ordered to attend Alcoholics Anonymous meetings, where he becomes convinced that his alcoholism is a potentially fatal disease.  Meanwhile, a statue of the Virgin Mary starts bleeding "out its ass" and Randy believes that he can be "cured" if it bleeds on him.',
   '"Bloody Mary (Nerve Endings)", often referred to as just "Bloody Mary", is an indie rock song performed by American alternative rock music group Silversun Pickups.  The song was written by Silversun Pickups, and produced by Jacknife Lee.  It serves as the lead-off single to their third studio album, "Neck of the Woods", which was released on May 8, 2012.  The song reached the top ten of the "Billboard" Alternative Songs chart in May 2012, peaking at number seven in June.',
   'A Bloody Mary is a cocktail containing vodka, tomato juice, and combinations of other spices and flavorings including Worcestershire sauce, Hot Sauce, piri piri sauce, beef consommé or bouillon, horseradish, celery, olives, salt, black pepper, cayenne pepper, lemon juice, lime juice and/or celery salt.',
   "The Bloody Mary Show is a multi-award-winning British comedy web series produced and written by director Darren Chadwick-Hussein.  The series is broadcast on the internet and premiered on September 7, 2012.  So far, seven episodes of season one have been made, with season two currently under development.  The show can be found distributed across the web including on Blip and YouTube.  The Bloody Mary Show follows a group of unconventional ghouls, who can be summoned from the afterlife by the living or are sent to haunt them.  The show focuses on main character Bloody Mary and her friends, Abdabs, Malevolent and Viscera, as they spend their days haunting the living, sharing their experiences and drinking at an underworld bar called Hemingway's, which was filmed in the oldest pub on the River Thames, 'The Mayflower.'",
   'Thinks ... is a 2001 novel by British author David Lodge.',
   'Arriving Somewhere... is the first live performance DVD by British progressive rock band Porcupine Tree.  Disc one is a full show from the "Deadwing" tour filmed by "Studio M" with nine High Def cameras at Park West, Chicago on 11 and 12 October 2005, edited by Lasse Hoile, with the soundtrack mixed in stereo and 5.1 surround sound by Steven Wilson, and mastered by Darcy Proper.  Disc two includes live performances on the German television show "Rockpalast", a promotional video for "Lazarus", the live films used as the backdrop for three songs, Gavin Harrison\'s "Cymbal Song", and a photo gallery with over 100 images.  The soundtrack to the DVD is available in FLAC and MP3 formats from the band\'s download store since April, 2007.  This audio edition is in the top 10 of the "Top Albums of 2007" chart of Rate Your Music website.  The DVD was re-released under Kscope record label on 21 April 2008 the same day of the regular release for the DVD-A edition of "Lightbulb Sun".',
   'be cast in a musical film.  He is currently busy writing his original screenplays; in hopes to bring them to fruition.',
   'Koi... Mil Gaya (English: "I.. .  Found Someone" ) is a 2003 Indian science fiction film directed by Rakesh Roshan (who also has a cameo role), starring Hrithik Roshan and Preity Zinta in the lead roles with Rekha playing an important supporting role.  Initially, Aishwarya Rai was offered the role of Nisha.  After she declined, the role went to Zinta.  The film was released on 8 August 2003.  It was shot in Kasauli, Nanital, Bhimtal and in Canada.',
   'After... is an adult Japanese visual novel developed by Ciel which was released on June 27, 2003 playable on the PC as a CD or a DVD.The early DVD version includes a guide book and soundtrack CD and the early CD version includes a guide book and a mouse pad.  Subsequent enhanced ports to the Dreamcast and to the PlayStation 2 as "After... ~Wasureemu Kizuna~" were released.  Both ports feature their own exclusive characters and new scenarios not in the original PC release.',
   'Thinks ... is a 2001 novel by British author David Lodge.',
   'Arriving Somewhere... is the first live performance DVD by British progressive rock band Porcupine Tree.  Disc one is a full show from the "Deadwing" tour filmed by "Studio M" with nine High Def cameras at Park West, Chicago on 11 and 12 October 2005, edited by Lasse Hoile, with the soundtrack mixed in stereo and 5.1 surround sound by Steven Wilson, and mastered by Darcy Proper.  Disc two includes live performances on the German television show "Rockpalast", a promotional video for "Lazarus", the live films used as the backdrop for three songs, Gavin Harrison\'s "Cymbal Song", and a photo gallery with over 100 images.  The soundtrack to the DVD is available in FLAC and MP3 formats from the band\'s download store since April, 2007.  This audio edition is in the top 10 of the "Top Albums of 2007" chart of Rate Your Music website.  The DVD was re-released under Kscope record label on 21 April 2008 the same day of the regular release for the DVD-A edition of "Lightbulb Sun".',
   'be cast in a musical film.  He is currently busy writing his original screenplays; in hopes to bring them to fruition.',
   'Koi... Mil Gaya (English: "I.. .  Found Someone" ) is a 2003 Indian science fiction film directed by Rakesh Roshan (who also has a cameo role), starring Hrithik Roshan and Preity Zinta in the lead roles with Rekha playing an important supporting role.  Initially, Aishwarya Rai was offered the role of Nisha.  After she declined, the role went to Zinta.  The film was released on 8 August 2003.  It was shot in Kasauli, Nanital, Bhimtal and in Canada.',
   'After... is an adult Japanese visual novel developed by Ciel which was released on June 27, 2003 playable on the PC as a CD or a DVD.The early DVD version includes a guide book and soundtrack CD and the early CD version includes a guide book and a mouse pad.  Subsequent enhanced ports to the Dreamcast and to the PlayStation 2 as "After... ~Wasureemu Kizuna~" were released.  Both ports feature their own exclusive characters and new scenarios not in the original PC release.'],
  'latency': 2.2386241230051382,
  'type': 'comparison',
  'num_titles_in_question': 0,
  'prompt_tokens': 5365,
  'completion_tokens': 18,
  'search': True},
 {'id': '5a7fe0b55542994857a76818',
  'question': 'Are The Maine and Black both from Tempe, Arizona?',
  'hop_counter': 3,
  'answer': 'no',
  'titles': ['The Maine (band)',
   'Tempe, Arizona',
   'Tempe Preparatory Academy',
   'Tyshane',
   'Cake (band)',
   'The Maine (band)',
   'Tempe, Arizona',
   'Tempe Preparatory Academy',
   'Tyshane',
   'Cake (band)',
   'Thinks ...',
   'Arriving Somewhere...',
   'Daniel Romer',
   'Koi... Mil Gaya',
   'After... (visual novel)'],
  'context': ['The Maine is an American rock band from Tempe, Arizona, formed in 2007.  Their first release, the EP "Stay Up, Get Down" was released in late 2007, followed by a five-song EP titled "The Way We Talk" on December 11, 2007.  The band\'s first full-length album, "Can\'t Stop Won\'t Stop" was released July 8, 2008. " ...And a Happy New Year" was released in December 2008.  Their second full-length album, "Black & White", (July 13, 2010) sold 22,634 copies in its first week.  On December 6, 2011, the group\'s third album, "Pioneer", was released and it peaked at No. 90 on the Billboard 200.  Their fourth full-length record "Forever Halloween"(June 4, 2013) reached No. 39 on the Billboard 200 by selling over 10,000 copies in its first week and was followed by its deluxe edition on June 17, 2014.  Their fifth studio album, "American Candy", was released on March 31, 2015. " Lovely Little Lonely", their sixth full-length record, was released on April 7, 2017.',
   'Tempe ( ; "Oidbaḍ" in Pima), also known as Hayden\'s Ferry during the territorial times of Arizona, is a city in Maricopa County, Arizona, United States, with the Census Bureau reporting a 2010 population of 161,719.  The city is named after the Vale of Tempe in Greece.  Tempe is located in the East Valley section of metropolitan Phoenix; it is bordered by Phoenix and Guadalupe on the west, Scottsdale on the north, Chandler on the south, and Mesa on the east.  Tempe is also the location of the main campus of Arizona State University.',
   'Tempe Preparatory Academy is a public charter school in Tempe, a suburb of Phoenix, Arizona in the United States.  Founded in 1996, Tempe Preparatory Academy (also known as Tempe Prep or TPA) offers a Great Books, core liberal arts curriculum centered on Western tradition, history, language, and literature.  Its motto is "Verum, Pulchrum, Bonum", meaning "Truth, Beauty, Goodness".  It is also the founding model for the Great Hearts Academies schools, with which it is otherwise unaffiliated.  Tempe Prep is an independently-governed public charter school.  The current headmaster is Dr. Wayne Porter.  Past headmasters include Dr. Thomas Butler, Mr. Andrew Zwernaman, Dr. Daniel Scoggin, Mr. Ron Bergez, Ms. Julie Boles, Mr. Hugh Hallman, Dr. Torren Baker and Dr. David Baum.',
   'Tyshane Thompson, currently known as Beam and formerly Tyshane and Elite, is an American hip hop producer.  In addition to his solo work, he formed the production duo 808&Elite with Matt Massaro.  He is the son of dancehall and gospel reggae pioneer Papa San.  According to Thompson\'s father, he started producing at age ten.  He first received notice when he produced for Andy Mineo on the tracks "Young", featuring KB, and "Michael Jackson", featuring Thi\'sl, Rich Perez, R-Swift, and Bubba Watson, from the album "Formerly Known" in 2011.  In 2012 he produced the highly popular, Jamaican-tinged song "Black Rose" by Lecrae on the mixtape "Church Clothes".  He also appeared in the final episode of the web-series "Saturday Morning Car-Tunez", created by Andy Mineo, where he helped remix the Puff Daddy song "It\'s All About the Benjamins".  On July 6, 2012, Thompson and Matt Massaro, under the name 808&Elite, released the single "Me Monster", featuring Andy Mineo, from their upcoming beat-tape, "Diamonds x Pearls".  The tape was made available two days later for free download exclusively through the Christian hip-hop website Rapzilla.  Thompson\'s talent was praised by critics when he and',
   "Cake (stylized CAKE) is an American alternative rock band from Sacramento, California.  Consisting of singer John McCrea, trumpeter Vince DiFiore, guitarist Xan McCurdy, bassist Gabe Nelson and drummer Paulo Baldi, the band has been noted for McCrea's sarcastic lyrics and monotone vocals, DiFiore's trumpet parts, and their wide-ranging musical influences, including country music, Mariachi, rock, funk, Iranian folk music and hip hop.",

In [4]:
res=await classical_rag(pilot,final_corpus_embed)
res

[{'titles': ['Manchester Airports Group',
   'Eastern Airways',
   'Manchester–Boston Regional Airport',
   'BA CityFlyer',
   'Humberside Airport'],
  'id': '5ade66f055429939a52fe8a0',
  'latency': 4.047700424999675,
  'question': "Easter Airways' head office is located at which airport owned by Manchester Airports Group?",
  'answer': 'unknown',
  'prompt_tokens': 607,
  'completion_tokens': 2},
 {'titles': ['Full Frontal (Australian TV series)',
   'Ricky Gervais',
   'The Ricky Gervais Show',
   'List of The Ricky Gervais Show episodes',
   "Chewin' the Fat"],
  'id': '5a7f924c55429969796c1aba',
  'latency': 9.300308680999478,
  'question': 'Which Star of British-Canadian-American satirical comedy, co starting with Ricky Gervais, began his career in sketch comedy series"Full Frontal" ?',
  'answer': 'Shaun Micallef',
  'prompt_tokens': 638,
  'completion_tokens': 6},
 {'titles': ['Kensington Runestone',
   'Kensington, Minnesota',
   'Pike Island',
   'Northern Cheyenne Indian Reservation',
   'Yarmouth Runic Stone'],
  'id': '5adfda5255429942ec259b5e',
  'latency': 6.678236505000314,
  'question': 'What county in Minnesota holds a 202 lb slab of greywacke covered in runes?',
  'answer': 'Douglas County',
  'prompt_tokens': 723,
  'completion_tokens': 4},
 {'titles': ['Flavio Santos',
   'Marquinhos (footballer, born June 1989)',
   'Dallas Cowboys',
   'Fred (footballer)',
   'Avaí FC'],
  'id': '5ae4e29855429908b63264a9',
  'latency': 3.9029316099995413,
  'question': 'Where does the team that Flavio de Jesús Santos  plays for play home games?',
  'answer': 'unknown',
  'prompt_tokens': 630,
  'completion_tokens': 2},
 {'titles': ['Keene, Kansas',
   'Bradford, Kansas',
   'Newbury, Kansas',
   'Wabaunsee, Kansas',
   'Kansas'],
  'id': '5ab8ed305542991b5579f046',
  'latency': 5.06167955500041,
  'question': 'Keene is an unincorporated community in Wabaunsee County, Kansas, in what federal republic composed of 50 states?',
  'answer': 'United States',
  'prompt_tokens': 335,
  'completion_tokens': 3},
 {'titles': ['Change (Taylor Swift song)',
   'Fearless (Taylor Swift album)',
   'Taylor Swift (album)',
   'Teardrops on My Guitar',
   'List of songs recorded by Taylor Swift'],
  'id': '5ae26197554299495565da51',
  'latency': 9.190269675000309,
  'question': 'American singer-songwriter, Taylor Swift, self-penned the song, Change, alongside Nathan Chapman, which was featured on her second studio album released by who?',
  'answer': 'Big Machine Records',
  'prompt_tokens': 983,
  'completion_tokens': 4},
 {'titles': ['2019 World Championships in Athletics',
   'Khalifa International Stadium',
   'World Games',
   '2007 Baseball World Cup',
   '2019 AFC Asian Cup'],
  'id': '5ae4db9c55429908b6326492',
  'latency': 12.757615518999955,
  'question': 'What was held in 2011 at the same stadium where the seventeenth edition of the IAAF World Championships is scheduled to be held in 2019?',
  'answer': '2011 AFC Asian Cup',
  'prompt_tokens': 681,
  'completion_tokens': 8},
 {'titles': ['Aspen Institute',
   'Project for the New American Century',
   'Independent Institute',
   'William Kristol',
   'The Daily Caller'],
  'id': '5ac2eb635542990b17b154a7',
  'latency': 9.192103580000548,
  'question': 'Where was the think tank founded by a neoconservative political analyst born in 1952 established?',
  'answer': 'unknown',
  'prompt_tokens': 697,
  'completion_tokens': 2},
 {'titles': ['Judy Lewis',
   'Jerry Lee Lewis',
   'Julia Lennon',
   'Maine Event',
   'Jaimee Foxworth'],
  'id': '5a80b9df5542992bc0c4a7ec',
  'latency': 12.650476153000454,
  'question': "What was the nickname of Judy Lewis's father?",
  'answer': 'The Killer',
  'prompt_tokens': 495,
  'completion_tokens': 3},
 {'titles': ['Dowd Report',
   'Hustle (2004 film)',
   '4192: The Crowning of the Hit King',
   'Pete Rose Jr.',
   'Ray Knight'],
  'id': '5ab2b7c1554299166977406a',
  'latency': 12.651964153000336,
  'question': 'What was the name of the lawyer who took the main role in the report that helped land Pete Rose a lifetime suspension from baseball?',
  'answer': 'unknown',
  'prompt_tokens': 710,
  'completion_tokens': 2},
 {'titles': ['Mona Leaves-a',
   'Mona Simpson (The Simpsons)',
   'I, (Annoyed Grunt)-bot',
   "Mom's the Word",
   'Lost Our Lisa'],
  'id': '5ab5b0f75542992aa134a38c',
  'latency': 12.652334031000464,
  'question': 'What episode did Mona Penelope Simpson  on the animated show "The Simpsons"die?',
  'answer': 'unknown',
  'prompt_tokens': 737,
  'completion_tokens': 2},
 {'titles': ['Spam Museum',
   'Hormel',
   'Spam (food)',
   "Luck's Incorporated",
   'Whataburger'],
  'id': '5ae306115542992decbdcdc4',
  'latency': 17.00055911199979,
  'question': 'What is the brand who makes canned meats that had its own cook off in Austin until 2007?',
  'answer': 'unknown',
  'prompt_tokens': 490,
  'completion_tokens': 2},
 {'titles': ['Realness (RuPaul album)',
   "RuPaul's Drag Race",
   'The Beatles (TV series)',
   'Glee (TV series)',
   'Rudolph the Red-Nosed Reindeer (TV special)'],
  'id': '5adcb4ae5542994734353774',
  'latency': 18.350927806999607,
  'question': "Which channel produced the ninth volume of the tv series that premiered as the same date as RuPaul's first album?",
  'answer': 'unknown',
  'prompt_tokens': 1285,
  'completion_tokens': 2},
 {'titles': ['K-Y Jelly',
   'YG Entertainment',
   'Johnson &amp; Johnson',
   'Yue Yuen Industrial Holdings',
   'IKEA'],
  'id': '5a875b2a5542993e715abf0f',
  'latency': 23.00775254400014,
  'question': 'What company founded in 1886 has owned the K-Y brand?',
  'answer': 'Reckitt Benckiser',
  'prompt_tokens': 769,
  'completion_tokens': 7},
 {'titles': ['Discofox',
   'John Travolta',
   'Saturday Night Fever',
   'Staying Alive (1983 film)',
   'Two of a Kind (1983 film)'],
  'id': '5a8ff83c55429916514e73f3',
  'latency': 20.793872880999515,
  'question': 'What role is played by John Travolta in the film that greatly influenced the two dances, the disco fox and the hustle?',
  'answer': 'Tony Manero',
  'prompt_tokens': 802,
  'completion_tokens': 4},
 {'titles': ['Hotel Splendide (film)',
   'Donald Pleasence',
   'Daniel Craig',
   'Hotel Splendide (1932 film)',
   'Casino Royale (2006 film)'],
  'id': '5a79eef75542996c55b2dca6',
  'latency': 20.691190483000355,
  'question': 'Hotel Splendide is a British film from 2000 that features which James Bond actor?',
  'answer': 'unknown',
  'prompt_tokens': 755,
  'completion_tokens': 2},
 {'titles': ['Why Is There Air?',
   'For Adults Only',
   'Excalibur Hotel and Casino',
   'MGM Grand Las Vegas',
   'Oh, Baby! (Bill Cosby album)'],
  'id': '5ae53b545542990ba0bbb23c',
  'latency': 23.114537014000234,
  'question': "Where does the hotel and casino located in which Bill Cosby's third album was recorded?",
  'answer': 'Flamingo Hotel',
  'prompt_tokens': 423,
  'completion_tokens': 5},
 {'titles': ['Grace Claxton',
   'Albany Great Danes',
   'Anton Villatoro',
   'Jamele Mason',
   'Harry Prowell'],
  'id': '5ae4bc7955429913cc2044e9',
  'latency': 26.40565457499997,
  'question': 'To which competition did the University at Albany, SUNY send a Puerto Rican hurdler and sprinter?',
  'answer': '2016 Summer Olympics',
  'prompt_tokens': 689,
  'completion_tokens': 7},
 {'titles': ['Welsh Rarebit (radio programme)',
   'BBC',
   'Eynon Evans',
   'Raidió Teilifís Éireann',
   'Keith Walsh'],
  'id': '5ab57673554299637185c5a3',
  'latency': 27.642060040000615,
  'question': 'What public service broadcaster with over 20,950 employees, aired the variety show Welsh Rarebit?',
  'answer': 'British Broadcasting Corporation (BBC)',
  'prompt_tokens': 560,
  'completion_tokens': 7},
 {'titles': ['Argentine cuisine',
   'Floribbean cuisine',
   'Nicaraguan cuisine',
   'Levantine cuisine',
   'Combination meal'],
  'id': '5ab3c48755429969a97a81b8',
  'latency': 26.407071919000373,
  'question': 'What cuisine is described as a cultural blending of Mediterranean influences (such as those created by Italian and Spanish populations)?',
  'answer': 'Argentine cuisine',
  'prompt_tokens': 849,
  'completion_tokens': 4},
 {'titles': ['When We Was Fab',
   'What Is Life',
   'Dark Horse (George Harrison song)',
   'Somewhere in England',
   'Teardrops (George Harrison song)'],
  'id': '5adffb4655429925eb1afbbf',
  'latency': 26.298763091000183,
  'question': "What year was George Harrison's top UK charted song voted the nations 11th favorite 1980s number?",
  'answer': 'unknown',
  'prompt_tokens': 926,
  'completion_tokens': 2},
 {'titles': ['Nineteen Eighty-Four',
   'Final Blackout',
   'Watership Down',
   'Quest (Anderson novelette)',
   'Fredric Warburg'],
  'id': '5a8468c95542990548d0b2b1',
  'latency': 29.1133434809999,
  'question': 'What British publisher published a dystopian novel in 1949 written by an English author?',
  'answer': 'unknown',
  'prompt_tokens': 700,
  'completion_tokens': 2},
 {'titles': ['The Journal of Computational Finance',
   'Scientific journal',
   'Economics and Human Biology',
   'PLOS ONE',
   'Lawrence A. Gordon'],
  'id': '5a7a749d5542994f819ef1e0',
  'latency': 32.41453140000067,
  'question': 'At what frequency an academic journal publishes which covers numerical and computational techniques to reduce any substantial losses or gains suffered by an individual or an organization?',
  'answer': 'quarterly',
  'prompt_tokens': 827,
  'completion_tokens': 3},
 {'titles': ['Electroconvulsive therapy',
   'Cryo-electron tomography',
   'No. 3 Elementary Flying Training School RAAF',
   '3rd Tactical Squadron',
   'Alvin Goldfarb'],
  'id': '5a901b985542995651fb50b0',
  'latency': 32.415810243000124,
  'question': 'What is 3/4 of the budget of the agency who  placed ECT machines  in the Class III category coming from?',
  'answer': 'unknown',
  'prompt_tokens': 749,
  'completion_tokens': 2},
 {'titles': ["St Wilfrid's Chapel, Church Norton",
   'Alford, Lincolnshire',
   'Constantine Bay',
   'St Pierre, Monmouthshire',
   'Gilford, New Hampshire'],
  'id': '5ac17b485542994ab5c67d65',
  'latency': 32.41612872400037,
  'question': "What coastal resort is about 11 miles south-east of St Wilfrid's Church?",
  'answer': 'unknown',
  'prompt_tokens': 700,
  'completion_tokens': 2},
 {'titles': ['Clavivox',
   'Raymond Scott',
   'George Whitefield Chadwick',
   'Alexander Alyabyev',
   'Mark Warnow'],
  'id': '5ae5c212554299546bf82f4b',
  'latency': 32.5191174269994,
  'question': 'The Clavivox was invented by an American composer who was born Harry Warnow in what year?',
  'answer': 'unknown',
  'prompt_tokens': 633,
  'completion_tokens': 2},
 {'titles': ['Hugh Grosvenor, 7th Duke of Westminster',
   'Gerald Grosvenor, 6th Duke of Westminster',
   'Robert Grosvenor, 1st Marquess of Westminster',
   'Duke of Westminster',
   'Gerald Grosvenor, 4th Duke of Westminster'],
  'id': '5ae618325542996de7b71b56',
  'latency': 36.99769373900017,
  'question': 'Gerald Grosvenor, 6th Duke of Westminster was succeeded by the British aristocrat who is estimated to be worth how much?',
  'answer': 'unknown',
  'prompt_tokens': 729,
  'completion_tokens': 2},
 {'titles': ['Aviation Hall of Fame and Museum of New Jersey',
   'South Jersey Regional Airport',
   'Teterboro Airport',
   'Trenton–Mercer Airport',
   'East Hampton Airport'],
  'id': '5ac3ad7f5542995ef918c1de',
  'latency': 37.139649069999905,
  'question': 'The Aviation Hall of Fame and Museum of New Jersey is located at the airport in which New Jersey county?',
  'answer': 'unknown',
  'prompt_tokens': 698,
  'completion_tokens': 2},
 {'titles': ['Mercedes-Benz Zetros',
   'Lockheed C-130 Hercules',
   'URO VAMTAC',
   'Airbus A400M Atlas',
   'Messerschmitt Me 323'],
  'id': '5a905d085542995651fb5147',
  'latency': 37.14101636899977,
  'question': 'How many variants are there of the military transport aircraft that the Mercedes-Benz Zetros truck was designed to be compatible with?',
  'answer': 'unknown',
  'prompt_tokens': 685,
  'completion_tokens': 2},
 {'titles': ['Maggie Gripenberg',
   'Gerd Neggo',
   'DARCEE',
   'Agrippina Vaganova',
   'Orff Schulwerk'],
  'id': '5ac27d2555429963665199dc',
  'latency': 38.3544251860003,
  'question': 'The teaching method that Maggie Gripenberg was the first to introduce to Finland is used to teach what?',
  'answer': 'movement',
  'prompt_tokens': 777,
  'completion_tokens': 2},
 {'titles': ['BA Connect',
   'Shreveport-Bossier City-Minden CSA',
   'Beaconsfield, Victoria',
   'Brooklyn',
   'Memphis metropolitan area'],
  'id': '5ac1ff2255429964131be2b3',
  'latency': 39.30718178499956,
  'question': 'In the 2011 census what was the population of suburban area in which BA Connect is headquartered ?',
  'answer': 'unknown',
  'prompt_tokens': 680,
  'completion_tokens': 2},
 {'titles': ['Underwater!',
   'Jane Russell',
   'Jayne Mansfield',
   'Jean Harlow',
   'Katharine Hepburn'],
  'id': '5a8361f35542996488c2e431',
  'latency': 44.554051725000136,
  'question': 'Underwater! is a 1955 adventure film starring an American film actress who was a leading sex symbol in what decades?',
  'answer': '1950s',
  'prompt_tokens': 467,
  'completion_tokens': 6},
 {'titles': ['Roger de Kirkpatrick',
   'Tower of London',
   'Roger de Clifford, 2nd Baron de Clifford',
   'Arundel Castle',
   'Baron Grey of Ruthyn'],
  'id': '5ae0800055429924de1b70db',
  'latency': 42.45943094699942,
  'question': 'In which Sottish Region is the castle in which] Sir Roger de Kirkpatrick was born ?  ',
  'answer': 'unknown',
  'prompt_tokens': 737,
  'completion_tokens': 2},
 {'titles': ['North Bend, Oregon',
   'Ney Matogrosso',
   'Delilah (radio host)',
   'Southwest Oregon Regional Airport',
   'Ronn Owens'],
  'id': '5a72a4645542991f9a20c54c',
  'latency': 43.54621111799952,
  'question': 'What notable radio personality was born in North Bend, Oregon?',
  'answer': 'Delilah',
  'prompt_tokens': 462,
  'completion_tokens': 4},
 {'titles': ['Ann Winterton',
   'Nicholas Winterton',
   'Alan Haselhurst',
   'John Lloyd Wharton',
   'Henry Brett (colonel)'],
  'id': '5a7217f255429971e9dc9260',
  'latency': 42.56850880300044,
  'question': 'Which Member of Parliament for Macclesfield was married to Jane Ann Winterton?',
  'answer': 'unknown',
  'prompt_tokens': 679,
  'completion_tokens': 2},
 {'titles': ['Phuture',
   'Horticulture Netting or Vegetable Support Net',
   'European Poker Tour',
   'Partus sequitur ventrem',
   'Louis Blériot'],
  'id': '5ae33f9a5542990afbd1e0f1',
  'latency': 47.27761182799986,
  'question': 'What did Phuture begin that spread to the United Kingdom and Europe',
  'answer': 'acid house records',
  'prompt_tokens': 576,
  'completion_tokens': 4},
 {'titles': ['Thomas J. Connolly',
   'Maine gubernatorial election, 1998',
   'Eliot Cutler',
   'Angus King',
   'Jon A. Lund'],
  'id': '5adc99d95542994ed6169baa',
  'latency': 46.25763032600025,
  'question': 'When is the American politician and attorney which Thomas J. Connolly an for Governor of Maine in 1998 against born ',
  'answer': 'unknown',
  'prompt_tokens': 580,
  'completion_tokens': 2},
 {'titles': ['PokerFace',
   'Alex Trebek',
   'Vanessa Rousso',
   'Dag Palovic',
   'Lai Van Sam'],
  'id': '5ac274fc55429963665199c1',
  'latency': 47.27911552799924,
  'question': 'The host of PokerFace is from where?',
  'answer': 'unknown',
  'prompt_tokens': 911,
  'completion_tokens': 2},
 {'titles': ['Ignite!',
   'Nolan Bushnell',
   'Lisa Brennan-Jobs',
   'Intel',
   'South Texas Business, Education &amp; Technology Academy'],
  'id': '5a81418455429903bc27b95f',
  'latency': 48.33231497399993,
  'question': 'Who is the mother of the Texas business man that co-founded Ignite! Learning, Inc?',
  'answer': 'unknown',
  'prompt_tokens': 621,
  'completion_tokens': 2},
 {'titles': ['Kasimir Bileski',
   'Canada',
   'American Border Peak',
   'Winnipeg',
   'Pennsylvania'],
  'id': '5a8a231a55429930ff3c0cb4',
  'latency': 49.73565694299941,
  'question': 'Kasimir Bileski was a noted stamp dealer based in a Canadian province that is bordered by which 2 US states?',
  'answer': 'unknown',
  'prompt_tokens': 617,
  'completion_tokens': 2},
 {'titles': ['Operation Amsterdam',
   'Jan Hammer',
   'Polka',
   'Armida (Dvořák)',
   'Moravia'],
  'id': '5ae6371155429929b0807af1',
  'latency': 52.081628514999466,
  'question': 'Which of the music composed for Operation Amsterdam originated in the middle of the 19th century in Bohemia, now part of the Czech Republic?',
  'answer': 'unknown',
  'prompt_tokens': 781,
  'completion_tokens': 2},
 {'titles': ['Metro West Ambulance',
   'Moda Center',
   'Wisconsin Center',
   'Quatama MAX Station',
   'The O2 Arena'],
  'id': '5a7e075c5542995f4f4023a3',
  'latency': 54.780253169999924,
  'question': 'Metro West Ambulance serves event support for the building in Portland formerly known as what?',
  'answer': 'Moda Center',
  'prompt_tokens': 774,
  'completion_tokens': 4},
 {'titles': ['General Survey Act',
   'General Revision Act',
   'Craig v. Boren',
   'Post–Civil Rights era in African-American history',
   'Public Law 113-167'],
  'id': '5abb07ec5542996cc5e49f55',
  'latency': 54.67848377300015,
  'question': 'The General Survey Act was passed shortly after the Supreme Court decision that discussed what concept?',
  'answer': 'national scope',
  'prompt_tokens': 768,
  'completion_tokens': 3},
 {'titles': ['Harrison Newey',
   'Chase Carey',
   'Stewart Grand Prix',
   'McLaren MP4-21',
   'Mick Schumacher'],
  'id': '5ab8627f5542990e739ec8da',
  'latency': 57.53951459200016,
  'question': 'Harrison Newey made his ADAC Formula 4 debut with a partner who is the son of who?',
  'answer': 'Michael Schumacher',
  'prompt_tokens': 615,
  'completion_tokens': 5},
 {'titles': ['Alex Rodriguez',
   'Berk Communications',
   'Ariel Award for Best Supporting Actor',
   'The Amazing Race en Discovery Channel 1',
   'The Amazing Race Canada 2'],
  'id': '5a862da855429960ec39b640',
  'latency': 59.37796912900012,
  'question': 'Who sponsors the award Alex Rodriguez won two of?',
  'answer': 'Berk Communication and Marketing Group',
  'prompt_tokens': 932,
  'completion_tokens': 7},
 {'titles': ['Collective for Living Cinema',
   'Lloyd Kaufman',
   'Dziga Vertov',
   'Jonathan Kaufer',
   'Edward Lachman'],
  'id': '5adec4695542992fa25da83a',
  'latency': 59.49193904299955,
  'question': 'The Collective for Living Cinema of Lower Manhattan featured work from what filmmaker also known as Denis Kaufman?',
  'answer': 'Dziga Vertov',
  'prompt_tokens': 747,
  'completion_tokens': 6},
 {'titles': ['Russell D. Moore',
   'Ethics &amp; Religious Liberty Commission',
   'Lee Rutland Scarborough',
   'Reed Lessing',
   'J. Philip Wogaman'],
  'id': '5ae57d3a554299546bf82ee6',
  'latency': 57.65180647000034,
  'question': 'After Russell D. Moore served at the Southern Baptist Theological Seminary he became the President of The Ethics & Religious Liberty Commission (ERLC) in what year?',
  'answer': 'unknown',
  'prompt_tokens': 778,
  'completion_tokens': 2},
 {'titles': ['WBYA',
   'Tusayan, Arizona',
   'WKVV',
   'Wheeling, West Virginia metropolitan area',
   'Bowie, Maryland'],
  'id': '5a7e23655542997cc2c47528',
  'latency': 59.379990956000256,
  'question': 'WBYA is a radio station licensed to a town with what population as of the 2010 census?',
  'answer': 'unknown',
  'prompt_tokens': 541,
  'completion_tokens': 2},
 {'titles': ['Jadwiga Szajna-Lewandowska',
   'Tatiana Nikolayeva',
   'Maria Szraiber',
   'Jan Hoffman',
   'Ignacy Jan Paderewski'],
  'id': '5a82fcbd55429954d2e2ebe8',
  'latency': 63.265324945999964,
  'question': 'Russia Soviet pianist, composer and teacher, Tatiana Nikolayeva taught what Polish pianist and music educator?',
  'answer': 'Maria Szraiber',
  'prompt_tokens': 407,
  'completion_tokens': 5},
 {'titles': ['Hugh Grosvenor, 7th Duke of Westminster',
   'Grosvenor Museum',

In [5]:
assert len(res) == len(pilot), len(res)
assert len({r["id"] for r in res}) == len(pilot)
print("ok:", len(res), "records, unique ids")

ok: 150 records, unique ids

In [6]:
classical_df=pd.DataFrame(res)
classical_df.to_parquet("../data/processed/classical_results.parquet")
classical_df.head()

,titles,id,latency,question,answer,prompt_tokens,completion_tokens
0,"[Manchester Airports Group, Eastern Airways, M...",5ade66f055429939a52fe8a0,4.047700,Easter Airways' head office is located at whic...,unknown,607,2
1,"[Full Frontal (Australian TV series), Ricky Ge...",5a7f924c55429969796c1aba,9.300309,Which Star of British-Canadian-American satiri...,Shaun Micallef,638,6
2,"[Kensington Runestone, Kensington, Minnesota, ...",5adfda5255429942ec259b5e,6.678237,What county in Minnesota holds a 202 lb slab o...,Douglas County,723,4
3,"[Flavio Santos, Marquinhos (footballer, born J...",5ae4e29855429908b63264a9,3.902932,Where does the team that Flavio de Jesús Santo...,unknown,630,2
4,"[Keene, Kansas, Bradford, Kansas, Newbury, Kan...",5ab8ed305542991b5579f046,5.061680,Keene is an unincorporated community in Wabaun...,United States,335,3